import React from "react";
import Head from "next/head";
import { Mulish } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from  "./Navbar"

const mulish = Mulish({ subsets: ["latin"] });

export default function Lyout(props: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div className={`${mulish.className}`}>
      <Navbar />
        {props.children}
      </div>
    </>
  );
}
